<window>
    <property>
        <width>1000</width>
        <height>1000</height>
        <background_color>white</background_color>
    </property>
    <rect>
        <property>
            <x>50</x>
            <y>50</y>
            <width>50</width>
            <height>100</height>
        </property>
    </rect>
    <circle>
        <property>
            <x>150</x>
            <y>150</y>
            <radius>30.2</radius>
        </property>
    </circle>
    <triangle>
        <property>
            <x>250</x>
            <y>250</y>
            <radius>30</radius>
            <color>red</color>
        </property>
    </triangle>
</window>