<window>
    <property>
        <width>1000</width>
        <height>1000</height>
        <background_color>white</background_color>
    </property>
    <rect>
        <property>
            <x>50</x>
            <y>50</y>
            <width>50</width>
            <height>100</height>
            <color>green</color>
        </property>
        <animation>
            <new_color>grey</new_color>
            <type>color</type>
            <event>none</event>
            <time>0.05</time>
            <reset_at_end>true</reset_at_end>
            <repeat>true</repeat>
            <break_time>0.05</break_time>
        </animation>
    </rect>
    <circle>
        <property>
            <x>150</x>
            <y>150</y>
            <radius>30.2</radius>
            <color>blue</color>
        </property>
    </circle>
    <triangle>
        <property>
            <x>250</x>
            <y>250</y>
            <radius>30</radius>
            <color>red</color>
        </property>
    </triangle>
    <image>
        <property>
            <x>540</x>
            <y>540</y>
            <src>dromadaire.jpg</src>
            <scale_x>0.4</scale_x>
            <scale_y>0.4</scale_y>
            <rotation>150</rotation>
        </property>
        <animation>
            <type>rotation</type>
            <event>none</event>
            <time>6</time>
            <reset_at_end>false</reset_at_end>
            <repeat>true</repeat>
            <break_time>0</break_time>
            <total_rotation_value>360</total_rotation_value>
        </animation>
    </image>
</window>